name: Build

on:
  push:
    branches:
      - "**"
  workflow_dispatch:

jobs:
 build:
   runs-on: ubuntu-latest
   steps:     
   - name: Checkout Repository
     uses: actions/checkout@v3
  
   - name: Setup .Net
     uses: actions/setup-dotnet@v3
     with:
       dotnet-version: '6.0'

   - name: Restore Dependencies
     run: dotnet restore ${{ github.workspace }}/scr/BranchCleaner/BranchCleaner.sln

   - name: Build Web Application
     run: dotnet build ${{ github.workspace }}/scr/BranchCleaner/BranchCleaner.sln
   - name: Run Test Cases
     run: dotnet test ${{ github.workspace }}/unit_test_case
